# nixpacks.toml

# Define providers for the environment
providers = ["python"]

# Define packages to install using Nix package manager
[phases.setup]
nixPkgs = ["libgl1-mesa-glx", "libglib2", "libsm6", "libxext6", "libxrender"]

# Start command for the application
[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT" 